### ISSUE TITLE
🐛 Bug Report: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by vitusan** [appwrite/sdk-for-web#108]
### 👟 Reproduction steps

install appwrite web sdk or the angular web sdk wrapper (ngx-appwrite);
follow configuration from tutorial at https://appwrite.io/docs/quick-starts/angular;
run ng s;
get error when loading page;

### 👍 Expected behavior

Not present the error.

### 👎 Actual Behavior

Found same issue here https://appwrite.io/threads/1279972579033219134

![image](https://github.com/user-attachments/assets/2146764e-56e1-49d8-b31d-76985414839e)

```
4:21:55 PM [vite] Internal server error: Cannot read properties of undefined (reading 'replace')
      at Client.setEndpoint (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-QDVDZWYS.js:258:89)
      at eval (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\ngx-appwrite.js:5475:14)
      at _ApplicationInitStatus.runInitializers (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-E6GZ4TPX.js:21108:26)
      at eval (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-E6GZ4TPX.js:22281:18)
      at _callAndReportToErrorHandler (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-E6GZ4TPX.js:21177:20)
      at eval (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-E6GZ4TPX.js:22279:12)
      at _ZoneDelegate.invoke (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\node_modules\.pnpm\zone.js@0.14.10\node_modules\zone.js\fesm2015\zone-node.js:369:28)
      at Object.onInvoke (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\.angular\cache\18.2.6\vite\deps_ssr\chunk-E6GZ4TPX.js:6817:25)
      at _ZoneDelegate.invoke (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\node_modules\.pnpm\zone.js@0.14.10\node_modules\zone.js\fesm2015\zone-node.js:368:34)
      at ZoneImpl.run (C:\Users\bode\Documents\repos\aazt\aaz-telecom-referral-app\node_modules\.pnpm\zone.js@0.14.10\node_modules\zone.js\fesm2015\zone-node.js:111:43)
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Self hosted version 1.5.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@vitusan, thanks for raising this issue! You may not have set an endpoint. To verify this, you can try to log `client.endpoint` before whatever method you're calling.

**Comment by stnguyen90** [comment]
Closing stale issue.
